app/urls.py
from django.urls import path
from . import views

app_name = "app"

urlpatterns = [
    path('', views.index, name="home"),
    path('<id>/delete', views.delete_view, name="delete"),
    path('<id>/update', views.edit_view, name="update"),
    path('<id>/select', views.select_view, name="read"),
]

crud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

app/models.py
from django.db import models


# Create your models here.
class UserFrom(models.Model):
    name = models.CharField(max_length=150)
    email = models.CharField(max_length=100, unique=True)
    subject = models.CharField(max_length=50)
    message = models.TextField()

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Feedback"
        verbose_name_plural = "Feedback"

app/forms.py
from django import forms
from .models import UserFrom


class DataForm(forms.ModelForm):
    name = forms.CharField(max_length=150, required=True, label='Name',
                           widget=forms.TextInput(attrs={'class': 'form-control'})
                           )

    email = forms.CharField(max_length=100, required=True, label='Email',
                            widget=forms.EmailInput(attrs={'class': 'form-control'})
                            )

    subject = forms.CharField(max_length=50, required=True, label='Subject',
                              widget=forms.TextInput(attrs={'class': 'form-control'})
                              )

    message = forms.CharField(max_length=250, required=True, label='Message',
                              widget=forms.Textarea(attrs={'class': 'form-control'})
                              )

    class Meta:
        model = UserFrom
        fields = ['name', 'email', 'subject', 'message']

app/views.py
from django.shortcuts import render, redirect
from .forms import DataForm
from django.contrib import messages
from .models import UserFrom


# Create your views here.

def index(request):
    if request.method == "POST":
        form = DataForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Request Completed')
            return redirect('app:home')
        return render(request, 'pages/home.html')
    else:
        form = DataForm()
        content = {
            'title': 'CrudApp::Home',
            'form': form,
            'data': UserFrom.objects.all(),
        }
        return render(request, 'pages/home.html', content)


def edit_view(request, id):
    data_edited = UserFrom.objects.get(id=id)
    if request.method == 'POST':
        data_edited.name = request.POST['name']
        data_edited.email = request.POST['email']
        data_edited.subject = request.POST['subject']
        data_edited.message = request.POST['message']
        data_edited.save()
        messages.success(request, "Data Updated Successfully")
        return redirect("app:home")
    else:
        return render(request, 'pages/edit.html', {'data': data_edited})


def delete_view(request, id):
    data_object = UserFrom.objects.get(id=id).delete()
    if data_object:
        messages.info(request, "Deleted Successfully")
        return redirect("app:home")


def select_view(request, id):
    read_data = UserFrom.objects.get(id=id)
    if read_data:
        content = {'selected_data': read_data}
        return render(request, "pages/data.html", content)

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% if title %}
        {{ title }}
    {% else %}
        CRUD APP::Home
    {% endif %}
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
</head>
<body>
{% block header %}

{% endblock header %}

<div class="container">

    {% block content %}

    {% endblock content %}
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
        crossorigin="anonymous"></script>
</body>
</html>

app/templates/pages/data.html
{% extends 'base.html' %}

{% block header %}
    <nav class="nav navbar bg-dark justify-content-center">
        <h1 class="text-primary">Select</h1>
    </nav>
{% endblock %}

{% block content %}
    <div class="row justify-content-center m-2">
        <div class="card" style="width: 18rem;">
            <ul class="list-group list-group-flush">
                <li class="list-group-item">Name: {{ selected_data.name }}</li>
                <li class="list-group-item">Email: {{ selected_data.email }}</li>
                <li class="list-group-item">Subject: {{ selected_data.subject }}</li>
                <li class="list-group-item">Message: {{ selected_data.message }}</li>
            </ul>
        </div>
    </div>
    <div class="col-md-2">
        <a href="{% url 'app:home' %}" class="btn btn-primary">Back</a>
    </div>
{% endblock content %}

app/templates/pages/edit.html
{% extends 'base.html' %}
{% block header %}
    <nav class="nav navbar justify-content-center bg-dark">
        <h1 class="text-primary">Update</h1>
    </nav>
{% endblock header %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="name">Name:</label>
            <input id="name" name="name" type="text" class="form-control" value="{{ data.name }}">
        </div>
        <div class="form-group">
            <label for="email">Email:</label>
            <input id="email" type="email" name="email" class="form-control" value="{{ data.email }}">
        </div>
        <div class="form-group">
            <label for="subject">Subject:</label>
            <input id="subject" type="text" name="subject" class="form-control" value="{{ data.subject }}">
        </div>
        <div class="form-group">
            <label for="message">Message:</label>
            <textarea id="message" name="message" cols="30" rows="10" class="form-control">{{ data.message }}</textarea>
        </div>
        <div class="d-flex mt-2">
            <input type="submit" value="Update" class="btn btn-primary">&nbsp;
            <a href="{% url 'app:home' %}" class="btn btn-primary">Back</a>
        </div>
    </form>
{% endblock content %}

app/templates/pages/home.html
{% extends 'base.html' %}

{% block header %}
    <nav class="nav navbar bg-dark justify-content-center">
        <h1 class="text-center text-primary">Crud Operation</h1>
    </nav>
    {% if messages %}
        {% for message in messages %}
            <div class="m-2">
                <div class="alert alert-success col-md-5 m-auto">{{ message }}</div>
            </div>
        {% endfor %}

    {% endif %}
{% endblock %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Add" class="btn btn-primary">
    </form>

    <hr/>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Email</th>
            <th>Subject</th>
            <th>Message</th>
            <th>Action</th>
        </tr>
        </thead>
        <tbody>
        {% for datum in data %}
            <tr>

                <td>{{ forloop.counter }}</td>
                <td>{{ datum.name }}</td>
                <td>{{ datum.email }}</td>
                <td>{{ datum.subject }}</td>
                <td>{{ datum.message }}</td>
                <td>
                    <a href="{% url 'app:read' datum.id %}">View</a> | <a
                        href="{% url 'app:update' datum.id %}">Update</a> | <a
                        href="{% url 'app:delete' datum.id %}">Delete</a>
                </td>

            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}